"""Initial table generation

Revision ID: 9158c06e96ed
Revises: 
Create Date: 2025-12-16 17:28:04.998722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9158c06e96ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedded_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('number_of_chunks', sa.Integer(), nullable=False),
    sa.Column('chunked_at', sa.DateTime(), nullable=False),
    sa.Column('page_length', sa.Integer(), nullable=False),
    sa.Column('embedded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embedded_metadata')
    # ### end Alembic commands ###
